import { describe, expect, test, beforeAll } from "bun:test";
import { spawnSync } from "node:child_process";
import { existsSync, readFileSync, statSync } from "node:fs";
import { join } from "node:path";

const repoRoot = join(import.meta.dir, "..");
const websiteRoot = join(repoRoot, "website");
const publicDir = join(websiteRoot, "public");
const buildScript = join(websiteRoot, "scripts", "build_site_data.py");
const siteDataJs = join(publicDir, "site_data.js");
const dataDir = join(publicDir, "data");
const indexHtml = join(publicDir, "index.html");

function pythonCmd(): string {
	for (const candidate of ["python", "python3", "py"]) {
		const r = spawnSync(candidate, ["--version"], { encoding: "utf8" });
		if (r.status === 0) return candidate;
	}
	return "python";
}

describe("website build", () => {
	let buildStdout = "";

	beforeAll(() => {
		const result = spawnSync(pythonCmd(), [buildScript], {
			cwd: repoRoot,
			encoding: "utf8",
		});
		buildStdout = (result.stdout || "") + (result.stderr || "");
		if (result.status !== 0) {
			throw new Error(`build_site_data.py failed:\n${buildStdout}`);
		}
	});

	test("build script writes site_data.js and mirrors raw JSON", () => {
		expect(existsSync(siteDataJs)).toBe(true);
		expect(statSync(siteDataJs).size).toBeGreaterThan(100_000);

		for (const f of ["functions.enriched.json", "typeDocumentation.json", "snippets.json"]) {
			const p = join(dataDir, f);
			expect(existsSync(p)).toBe(true);
			expect(statSync(p).size).toBeGreaterThan(0);
		}
	});

	test("site_data.js exposes window.SITE_DATA with the expected shape", () => {
		const js = readFileSync(siteDataJs, "utf8");
		expect(js).toStartWith("// Generated by");
		expect(js).toInclude("window.SITE_DATA = ");

		const jsonStart = js.indexOf("{");
		const jsonEnd = js.lastIndexOf("}");
		expect(jsonStart).toBeGreaterThan(0);
		expect(jsonEnd).toBeGreaterThan(jsonStart);
		const payload = JSON.parse(js.slice(jsonStart, jsonEnd + 1));

		expect(payload.stats).toBeDefined();
		expect(payload.stats.functions).toBeGreaterThan(1000);
		expect(payload.stats.types).toBeGreaterThan(100);
		expect(payload.stats.snippets).toBeGreaterThan(0);

		expect(Array.isArray(payload.functions)).toBe(true);
		expect(Array.isArray(payload.types)).toBe(true);
		expect(Array.isArray(payload.snippets)).toBe(true);
		expect(payload.functions.length).toBe(payload.stats.functions);
		expect(payload.types.length).toBe(payload.stats.types);
		expect(payload.snippets.length).toBe(payload.stats.snippets);

		const f0 = payload.functions[0];
		expect(typeof f0.name).toBe("string");
		expect(typeof f0.signature).toBe("string");
		expect(typeof f0.category).toBe("string");

		const t0 = payload.types[0];
		expect(typeof t0.name).toBe("string");
		expect(typeof t0.group).toBe("string");

		const s0 = payload.snippets[0];
		expect(typeof s0.label).toBe("string");
		expect(typeof s0.body).toBe("string");
	});

	test("build script logs the expected counts", () => {
		expect(buildStdout).toInclude("functions :");
		expect(buildStdout).toInclude("types     :");
		expect(buildStdout).toInclude("snippets  :");
	});
});

describe("website html", () => {
	let html = "";
	beforeAll(() => {
		html = readFileSync(indexHtml, "utf8");
	});

	test("includes the language-server logo and favicon", () => {
		expect(html).toInclude('href="logo.png"');
		expect(html).toInclude('src="logo.png"');
		expect(html).toInclude('class="logo-img"');
		expect(existsSync(join(publicDir, "logo.png"))).toBe(true);
	});

	test("loads site_data.js, prism, and required language components", () => {
		expect(html).toInclude("site_data.js");
		expect(html).toInclude("vendor/prism/prism.min.js");
		expect(html).toInclude("vendor/prism/prism-clike.min.js");
		expect(html).toInclude("vendor/prism/prism-bash.min.js");
		expect(html).toInclude("vendor/prism/prism-tomorrow.min.css");
		expect(html).toInclude("prism-12dpl.js");
		expect(existsSync(join(publicDir, "prism-12dpl.js"))).toBe(true);

		// Vendored Prism assets must be self-hosted, not loaded from a CDN.
		const vendorDir = join(publicDir, "vendor", "prism");
		for (const f of ["prism.min.js", "prism-clike.min.js", "prism-bash.min.js", "prism-tomorrow.min.css"]) {
			expect(existsSync(join(vendorDir, f))).toBe(true);
		}
		expect(html).not.toMatch(/<script[^>]+src="https?:\/\/[^"]+"/);
		expect(html).not.toMatch(/<link[^>]+rel="stylesheet"[^>]+href="https?:\/\/[^"]+"/);
	});

	test("Getting Started covers VS Code + extension install", () => {
		expect(html).toInclude("Install VS Code");
		expect(html).toInclude("code.visualstudio.com/Download");
		expect(html).toInclude("nightworks.12dpl-lang-server");
		expect(html).toInclude("Marketplace");
	});

	test("compiling section is present and linked from sidebar", () => {
		expect(html).toInclude('id="compiling"');
		expect(html).toInclude('data-section="compiling"');
		expect(html).toInclude("cc4d.exe");
	});

	test("every <pre><code> block has a language-* class", () => {
		const blocks = [...html.matchAll(/<pre>\s*<code\b([^>]*)>/g)];
		expect(blocks.length).toBeGreaterThan(0);
		for (const m of blocks) {
			expect(m[1]).toMatch(/class="language-[a-z0-9]+"/);
		}
	});

	test("12dpl code blocks use the custom 12dpl grammar (not cpp)", () => {
		expect(html).not.toInclude("language-cpp");
		expect(html).toInclude('class="language-12dpl"');
	});

	test("dead links have been pruned", () => {
		expect(html).not.toInclude('href="calls/index.html"');
		expect(html).not.toInclude("logo-badge");
	});

	test("sidebar references the new sections", () => {
		expect(html).toInclude('data-section="getting-started"');
		expect(html).toInclude("Install VS Code &amp; Extension");
	});

	test("branding uses '12dPL Docs' and 'Language Server'", () => {
		expect(html).toInclude(">12dPL Docs<");
		expect(html).toInclude(">Language Server<");
		expect(html).not.toInclude(">PL Docs<");
		expect(html).not.toInclude(">Lang Server<");
	});

	test("About is its own section reachable via a header button", () => {
		expect(html).toInclude('id="about"');
		expect(html).toInclude('data-section="about"');
		expect(html).toInclude(">About<");
		expect(html).not.toInclude('class="site-footer"');
	});

	test("About section contains the required legal disclaimers", () => {
		expect(html).toInclude("not official 12dPL documentation");
		expect(html).toInclude("not a replacement");
		expect(html).toInclude("No affiliation");
		expect(html).toInclude("No warranty");
		expect(html).toInclude("Limitation of liability");
		expect(html).toInclude("Use at your own risk");
		expect(html).toInclude("12d Solutions");
		expect(html).toInclude("MIT");
		expect(html).toInclude('id="footerYear"');
	});
});

describe("prism-12dpl grammar", () => {
	test("registers a self-contained 12dpl language", () => {
		const src = readFileSync(join(publicDir, "prism-12dpl.js"), "utf8");
		const stub: any = {
			Prism: { languages: {} },
			document: {
				readyState: "complete",
				addEventListener() { /* no-op */ },
			},
		};
		// The script reads `window.Prism` — provide it via the function's `this`/scope.
		const fn = new Function("window", "document", "Prism", src);
		fn(stub, stub.document, stub.Prism);

		const lang = stub.Prism.languages["12dpl"];
		expect(lang).toBeDefined();
		expect(stub.Prism.languages["12dPL"]).toBe(lang);

		for (const key of ["comment", "string", "class-name", "keyword", "boolean", "function", "number", "operator", "punctuation", "macro"]) {
			expect(lang[key]).toBeDefined();
		}

		const classNameRe = lang["class-name"] as RegExp;
		for (const t of ["Text", "Integer", "Real", "Element", "Model", "Panel", "Vector3", "void"]) {
			expect(t).toMatch(classNameRe);
		}
		const fnRe = lang["function"] as RegExp;
		expect("To_text(").toMatch(fnRe);
		expect("Print(").toMatch(fnRe);
		expect("not_a_call").not.toMatch(fnRe);

		const kwRe = lang["keyword"] as RegExp;
		for (const k of ["if", "else", "for", "while", "return", "persistent"]) {
			expect(k).toMatch(kwRe);
		}
	});
});

describe("SEO meta tags", () => {
	let html = "";
	beforeAll(() => {
		html = readFileSync(indexHtml, "utf8");
	});

	test("includes description, keywords, robots, theme-color", () => {
		expect(html).toMatch(/<meta\s+name="description"\s+content="[^"]+12dPL[^"]*"/);
		expect(html).toMatch(/<meta\s+name="keywords"\s+content="[^"]+"/);
		expect(html).toMatch(/<meta\s+name="robots"\s+content="[^"]*index, follow[^"]*"/);
		expect(html).toMatch(/<meta\s+name="googlebot"/);
		expect(html).toMatch(/<meta\s+name="bingbot"/);
		expect(html).toMatch(/<meta\s+name="theme-color"/);
	});

	test("includes canonical, sitemap link, and favicon variants", () => {
		expect(html).toMatch(/<link\s+rel="canonical"\s+href="https:\/\/[^"]+"/);
		expect(html).toMatch(/<link\s+rel="sitemap"\s+type="application\/xml"\s+href="\/sitemap\.xml"/);
		expect(html).toMatch(/<link\s+rel="apple-touch-icon"/);
	});

	test("includes Open Graph tags", () => {
		for (const prop of ["og:type", "og:site_name", "og:title", "og:description", "og:url", "og:image"]) {
			expect(html).toInclude(`property="${prop}"`);
		}
	});

	test("includes Twitter card tags", () => {
		for (const name of ["twitter:card", "twitter:title", "twitter:description", "twitter:image"]) {
			expect(html).toInclude(`name="${name}"`);
		}
	});

	test("includes JSON-LD structured data", () => {
		const m = html.match(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/);
		expect(m).not.toBeNull();
		const parsed = JSON.parse(m![1]);
		expect(parsed["@context"]).toBe("https://schema.org");
		expect(Array.isArray(parsed["@graph"])).toBe(true);
		const types = parsed["@graph"].map((n: any) => n["@type"]);
		expect(types).toContain("WebSite");
		expect(types).toContain("SoftwareSourceCode");
		expect(types).toContain("TechArticle");
	});
});

describe("robots.txt and sitemap.xml", () => {
	test("robots.txt allows everything and lists AI bots explicitly", () => {
		const robotsPath = join(publicDir, "robots.txt");
		expect(existsSync(robotsPath)).toBe(true);
		const robots = readFileSync(robotsPath, "utf8");

		expect(robots).toMatch(/^User-agent:\s*\*\s*$/m);
		expect(robots).toMatch(/^Allow:\s*\/\s*$/m);

		for (const bot of ["GPTBot", "ClaudeBot", "anthropic-ai", "CCBot", "Google-Extended", "PerplexityBot", "Bytespider"]) {
			expect(robots).toInclude(`User-agent: ${bot}`);
		}

		expect(robots).toMatch(/^Sitemap:\s*https?:\/\/.+\/sitemap\.xml\s*$/m);
		expect(robots).not.toMatch(/^Disallow:\s*\/\s*$/m);
	});

	test("sitemap.xml is well-formed and lists key sections", () => {
		const sitemapPath = join(publicDir, "sitemap.xml");
		expect(existsSync(sitemapPath)).toBe(true);
		const xml = readFileSync(sitemapPath, "utf8");

		expect(xml).toStartWith('<?xml version="1.0" encoding="UTF-8"?>');
		expect(xml).toInclude('xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"');
		expect(xml).toInclude("<urlset");
		expect(xml).toInclude("</urlset>");

		const locs = [...xml.matchAll(/<loc>([^<]+)<\/loc>/g)].map(m => m[1]);
		expect(locs.length).toBeGreaterThan(20);
		expect(locs.some(l => l.endsWith("/"))).toBe(true);
		expect(locs.some(l => l.includes("#about"))).toBe(true);
		expect(locs.some(l => l.includes("#all-calls"))).toBe(true);
		expect(locs.some(l => l.includes("#snippets"))).toBe(true);
	});
});
